name: rectran
description: Voice recording and transcription app following Material Design 3 principles.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  provider: ^6.1.2
  intl: ^0.19.0
  uuid: ^4.5.0
  audioplayers: ^6.1.0
  record: 5.1.0
  http: ^1.2.2
  flutter_dotenv: ^5.2.1
  path_provider: ^2.1.5
  share_plus: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

dependency_overrides:
  record_linux: 0.7.1
  record_platform_interface: 1.1.0

flutter:
  uses-material-design: true
  assets:
    - .env
